import { AppMetadata } from '../types/os';

export const SYSTEM_APPS: AppMetadata[] = [
  {
    id: 'settings',
    name: 'Settings',
    icon: 'Settings',
    description: 'Personalize wallpaper, dynamic Material You colors, display and system',
    category: 'system',
    pinnedToDock: false,
    defaultWidth: 720,
    defaultHeight: 520,
  },
  {
    id: 'files',
    name: 'Files',
    icon: 'Folder',
    description: 'Browse local downloads, documents, pictures, and music',
    category: 'system',
    pinnedToDock: true,
    defaultWidth: 780,
    defaultHeight: 520,
  },
  {
    id: 'browser',
    name: 'Edge Web',
    icon: 'Compass',
    description: 'Explore the web with Material You search and curated bookmarks',
    category: 'utility',
    pinnedToDock: true,
    defaultWidth: 840,
    defaultHeight: 560,
  },
  {
    id: 'notes',
    name: 'Notes',
    icon: 'FileText',
    description: 'Quick notes, thoughts, and ideas with dynamic pastel labels',
    category: 'utility',
    pinnedToDock: true,
    defaultWidth: 720,
    defaultHeight: 480,
  },
  {
    id: 'music',
    name: 'Spotify Music',
    icon: 'Disc',
    description: 'Lofi beats and chill tracks with interactive audio visualizer',
    category: 'media',
    pinnedToDock: true,
    defaultWidth: 700,
    defaultHeight: 490,
  },
  {
    id: 'chat',
    name: 'ChatGPT',
    icon: 'Bot',
    description: 'AI Companion powered by interactive Material You assistant',
    category: 'utility',
    pinnedToDock: true,
    defaultWidth: 680,
    defaultHeight: 540,
  },
  {
    id: 'photos',
    name: 'Photos',
    icon: 'Image',
    description: 'View gallery photos, high-res wallpapers, and set desktop backgrounds',
    category: 'media',
    pinnedToDock: true,
    defaultWidth: 760,
    defaultHeight: 520,
  },
  {
    id: 'calculator',
    name: 'Calculator',
    icon: 'Calculator',
    description: 'Material You dynamic colored scientific calculator',
    category: 'utility',
    pinnedToDock: false,
    defaultWidth: 360,
    defaultHeight: 500,
  },
  {
    id: 'terminal',
    name: 'Terminal',
    icon: 'Terminal',
    description: 'WebOS command shell with Neofetch, system stats, and bash utils',
    category: 'utility',
    pinnedToDock: false,
    defaultWidth: 680,
    defaultHeight: 440,
  },
  {
    id: 'calendar',
    name: 'Calendar',
    icon: 'Calendar',
    description: 'Schedule, events, and monthly planner with festive calendar',
    category: 'utility',
    pinnedToDock: false,
    defaultWidth: 740,
    defaultHeight: 500,
  },
  {
    id: 'weather',
    name: 'Weather',
    icon: 'CloudSun',
    description: 'Live atmospheric conditions, hourly radar, and 7-day forecast',
    category: 'utility',
    pinnedToDock: false,
    defaultWidth: 660,
    defaultHeight: 480,
  },
  {
    id: 'mail',
    name: 'Mail',
    icon: 'Mail',
    description: 'Inbox, drafts, and system notifications',
    category: 'social',
    pinnedToDock: false,
    defaultWidth: 720,
    defaultHeight: 480,
  },
];
